# Generated by Django 2.1.7 on 2019-02-21 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_byte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubcategory',
            name='root_category',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='ask_byte.QuestionCategory'),
        ),
        migrations.DeleteModel(
            name='QuestionSubcategory',
        ),
    ]
