# Generated by Django 2.1.7 on 2019-02-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_byte', '0004_auto_20190221_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='ask_byte.QuestionCategory'),
        ),
    ]
