# Generated by Django 2.1.7 on 2019-03-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_byte', '0005_auto_20190221_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestion',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
